<?php
/**
 * Content Manager
 *
 * @package GeminiCommandCenter
 */

// If this file is called directly, abort.
if (!defined('WPINC')) {
    die;
}

/**
 * Class Gemini_CC_Content_Manager
 */
class Gemini_CC_Content_Manager {
    
    /**
     * Constructor
     */
    public function __construct() {
        add_action('rest_api_init', array($this, 'register_content_routes'));
    }
    
    /**
     * Register content-related REST routes
     */
    public function register_content_routes() {
        register_rest_route('gemini-cc/v1', '/content/generate-article', array(
            'methods' => 'POST',
            'callback' => array($this, 'generate_article'),
            'permission_callback' => array($this, 'check_permissions'),
            'args' => array(
                'topic' => array(
                    'required' => true,
                    'type' => 'string',
                    'sanitize_callback' => 'sanitize_text_field'
                ),
                'keywords' => array(
                    'required' => false,
                    'type' => 'string',
                    'sanitize_callback' => 'sanitize_text_field'
                ),
                'tone' => array(
                    'required' => false,
                    'type' => 'string',
                    'sanitize_callback' => 'sanitize_text_field'
                )
            )
        ));
        
        register_rest_route('gemini-cc/v1', '/content/save-draft', array(
            'methods' => 'POST',
            'callback' => array($this, 'save_draft'),
            'permission_callback' => array($this, 'check_permissions'),
            'args' => array(
                'title' => array(
                    'required' => true,
                    'type' => 'string',
                    'sanitize_callback' => 'sanitize_text_field'
                ),
                'content' => array(
                    'required' => true,
                    'type' => 'string'
                )
            )
        ));
    }
    
    /**
     * Check permissions
     */
    public function check_permissions() {
        return current_user_can('edit_posts');
    }
    
    /**
     * Generate article using AI
     */
    public function generate_article($request) {
        $topic = $request->get_param('topic');
        $keywords = $request->get_param('keywords');
        $tone = $request->get_param('tone');
        
        // This would integrate with Gemini API to generate content
        $generated_content = sprintf(
            '<h1>%s</h1><p>This is a demo article about %s. In a full implementation, this content would be generated by the Gemini AI API based on the provided topic, keywords (%s), and tone (%s).</p>',
            esc_html($topic),
            esc_html($topic),
            esc_html($keywords),
            esc_html($tone)
        );
        
        return rest_ensure_response(array(
            'success' => true,
            'content' => $generated_content,
            'title' => $topic
        ));
    }
    
    /**
     * Save article as draft
     */
    public function save_draft($request) {
        $title = $request->get_param('title');
        $content = $request->get_param('content');
        
        $post_data = array(
            'post_title' => $title,
            'post_content' => wp_kses_post($content),
            'post_status' => 'draft',
            'post_type' => 'post',
            'post_author' => get_current_user_id()
        );
        
        $post_id = wp_insert_post($post_data);
        
        if (is_wp_error($post_id)) {
            return new WP_Error('save_failed', __('Failed to save draft', 'gemini-command-center'), array('status' => 500));
        }
        
        return rest_ensure_response(array(
            'success' => true,
            'post_id' => $post_id,
            'edit_url' => admin_url('post.php?post=' . $post_id . '&action=edit'),
            'message' => __('Draft saved successfully', 'gemini-command-center')
        ));
    }
}